services:
  waguri-discord-bot:
    image: ghcr.io/simmuuu/waguri-discord-bot
    restart: on-failure:3
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    network_mode: host
    labels:
      - "io.containers.autoupdate=registry"
